"""add conditions and condition_medications tables

Revision ID: eae5df4e533f
Revises: 26c96e5e9a83
Create Date: 2026-04-12 00:01:51.993380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae5df4e533f'
down_revision: Union[str, Sequence[str], None] = '26c96e5e9a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_conditions_id'), 'conditions', ['id'], unique=False)
    op.create_table('condition_medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condition_id', 'medication_id')
    )
    op.create_index(op.f('ix_condition_medications_id'), 'condition_medications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_condition_medications_id'), table_name='condition_medications')
    op.drop_table('condition_medications')
    op.drop_index(op.f('ix_conditions_id'), table_name='conditions')
    op.drop_table('conditions')
    # ### end Alembic commands ###
