"""add caregiver fields and missed dose tracking

Revision ID: f20cf3afdc1a
Revises: f905549354c6
Create Date: 2026-04-12 23:47:52.059026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20cf3afdc1a'
down_revision: Union[str, Sequence[str], None] = 'f905549354c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('patient_medications') as batch_op:
        batch_op.add_column(sa.Column('consecutive_missed_doses', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_reminded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_taken_at', sa.DateTime(), nullable=True))
    with op.batch_alter_table('patients') as batch_op:
        batch_op.add_column(sa.Column('caregiver_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('caregiver_telegram_id', sa.String(length=30), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'caregiver_telegram_id')
    op.drop_column('patients', 'caregiver_name')
    op.drop_column('patient_medications', 'last_taken_at')
    op.drop_column('patient_medications', 'last_reminded_at')
    op.drop_column('patient_medications', 'consecutive_missed_doses')
    # ### end Alembic commands ###
