"""add frequency and reminder_times to patient_medications

Revision ID: f905549354c6
Revises: eae5df4e533f
Create Date: 2026-04-12 23:26:44.252612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f905549354c6'
down_revision: Union[str, Sequence[str], None] = 'eae5df4e533f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('patient_medications') as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.String(length=50), nullable=False, server_default='once_daily'))
        batch_op.add_column(sa.Column('reminder_times', sa.JSON(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_medications', 'reminder_times')
    op.drop_column('patient_medications', 'frequency')
    # ### end Alembic commands ###
